import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { RetroGrid } from "@/app/components/grid";
import Image from "next/image";
import Space from "./space.jpg";
import { IBM_Plex_Mono } from "next/font/google";

const ibm = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-ibm",
});

const retroTech = localFont({
  src: "./fonts/RETROTECH.ttf",
  variable: "--font-retro-tech",
  weight: "100 900",
});

const lcd = localFont({
  src: "./fonts/LCD.ttf",
  variable: "--font-lcd",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${retroTech.variable} ${ibm.variable} ${lcd.variable} antialiased w-full min-h-screen relative`}
      >
        <div className="fixed inset-0 z-0">
          <RetroGrid />{" "}
          <Image src={Space} alt="space" fill className="opacity-10" />
        </div>
        <main className="relative z-10 w-full">{children}</main>
      </body>
    </html>
  );
}
